# Generated by Django 2.0.2 on 2018-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=1000)),
                ('occupancy', models.IntegerField()),
                ('checked_in', models.BooleanField()),
                ('checked_out', models.BooleanField()),
                ('ready', models.BooleanField()),
            ],
        ),
    ]
