# Generated by Django 2.0.2 on 2018-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180705_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.IntegerField(),
        ),
    ]
