# Generated by Django 2.0.2 on 2018-07-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0001_initial'),
        ('rooms', '0005_auto_20180705_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='occupancy',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='room_types.RoomType'),
            preserve_default=False,
        ),
    ]
