# Generated by Django 2.0.2 on 2018-07-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0001_initial'),
        ('rooms', '0007_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='room_types.RoomType'),
            preserve_default=False,
        ),
    ]
