# Generated by Django 2.0.2 on 2018-07-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
