# Generated by Django 2.0.2 on 2018-07-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0002_bed_occupancy'),
        ('rooms', '0009_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='room_types.RoomType'),
            preserve_default=False,
        ),
    ]
