# Generated by Django 2.0.2 on 2018-07-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_email'),
        ('rooms', '0011_auto_20180707_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property'),
            preserve_default=False,
        ),
    ]
