# Generated by Django 2.0.2 on 2018-07-23 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property'),
        ),
    ]
