language: python
services:
  - postgresql
python:
 - "3.6"
 - "nightly"
install:
 - "pip install -r requirements.txt"
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
script: python manage.py test properties/tests room_types/tests