language: python
services:
  - postgresql
python:
 - "3.6"
 - "nightly"
install:
 - "pip install -r requirements.txt"
before_script:
 - psql -c "CREATE DATABASE test_propertymanagerdb;" -U postgres
 - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
 - python manage.py migrate
 - python manage.py makemigrations
 - python manage.py migrate
script: python manage.py test properties/tests