TEST_ROOMTYPE_NAME = 'test_roomtype_name'
TEST_ROOMTYPE_NAME_MAX_LENGTH = 80
TEST_ROOMTYPE_IMAGE = 'test_roomtype_image.png'
TEST_NUMBEDS = 3
TEST_ROOM_RATE = 100
TEST_DEFAULT_RATE = 50
TEST_DEFAULT_NUMBEDS = 1

TEST_BED_NAME = 'King Bed'
TEST_BED_NAME_MAX_LENGTH = 80
TEST_BED_OCCUPANCY = 2

