# Generated by Django 2.0.2 on 2018-07-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guests.Guest')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Room')),
            ],
        ),
    ]
