# Generated by Django 2.0.2 on 2018-07-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_email'),
        ('room_types', '0004_auto_20180707_2231'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.Property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='room_types.RoomType'),
            preserve_default=False,
        ),
    ]
