# Generated by Django 2.0.2 on 2018-07-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20180723_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_types',
        ),
    ]
