# Generated by Django 2.0.2 on 2018-07-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_room_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='property',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rooms',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Room'),
        ),
    ]
