# Generated by Django 2.0.2 on 2018-07-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='email',
        ),
    ]
