# Generated by Django 2.0.2 on 2018-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=80)),
                ('last_name', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
            ],
        ),
    ]
