# Generated by Django 2.0.2 on 2018-07-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_types', '0002_bed_occupancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='beds',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='occupancy',
            new_name='num_beds',
        ),
    ]
